### ISSUE TITLE
aprsshm.c: 2 * broken error checking on shmat

### ISSUE THREAD

**Issue by dcb314** [n2ygk/aprsdigi#3]
1.
aprsshm.c:93:50: warning: ordered comparison of pointer with integer zero [-Wextra]

Source code is

  if ((pktseg = (struct pktseg *)shmat(seg,0,0)) < 0) {

Suggest RTFM. Better source code might be

   if ((pktseg = (struct pktseg *)shmat(seg,0,0)) == (void *) -1) {

2.

aprsshm.c:167:59: warning: ordered comparison of pointer with integer zero [-Wextra]

Duplicate.

**Comment by n2ygk** [comment]
Feel free to submit a PR.

**Comment by dcb314** [comment]
I have no idea how to "submit a PR". I've had a look around in the
package and the source code, no clues there that I could see.

My bug report provides all the technical detail required.

I am happy for someone else to "submit a PR".

**Comment by n2ygk** [comment]
https://help.github.com/en/articles/creating-a-pull-request

**Comment by n2ygk** [comment]
Suggest you look at [direwolf](https://github.com/wb2osz/direwolf) instead.
